name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install SSH key
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Hostinger
      env:
        HOSTINGER_SERVER: ${{ secrets.HOSTINGER_SERVER }}
        HOSTINGER_USER: ${{ secrets.HOSTINGER_USER }}
        APP_SECRET: ${{ secrets.APP_SECRET }}
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
        MAILER_DSN: ${{ secrets.MAILER_DSN }}
        API_FT_CLIENT_ID: ${{ secrets.API_FT_CLIENT_ID }}
        API_FT_CLIENT_SECRET: ${{ secrets.API_FT_CLIENT_SECRET }}
      run: |
        ssh -p 65002 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $HOSTINGER_USER@$HOSTINGER_SERVER '
          cd public_html/french_towns_map/ &&
          git fetch origin main &&
          git reset --hard origin/main &&
          cat > .env <<EOL
          sed -i "s|%APP_SECRET%|$APP_SECRET|g" .env &&
          sed -i "s|%DATABASE_URL%|$DATABASE_URL|g" .env &&
          sed -i "s|%MAILER_DSN%|$MAILER_DSN|g" .env &&
          sed -i "s|%API_FT_CLIENT_ID%|$API_FT_CLIENT_ID|g" .env &&
          sed -i "s|%API_FT_CLIENT_SECRET%|$API_FT_CLIENT_SECRET|g" .env &&
          ../composer.phar install --no-dev --optimize-autoloader &&
          php bin/console cache:clear --env=prod &&
          php bin/console doctrine:migrations:migrate --no-interaction --allow-no-migration &&
          php bin/console asset-map:compile --env=prod'
